package constant

const USER_NOT_FOUND string = "USER_NOT_FOUND"
const EMAIL_ALREADY_EXISTS string = "EMAIL_ALREADY_EXISTS"
const CREATE_TOKEN_FAILURE string = "CREATE_TOKEN_FAILURE"
const INCRRECT_PASSWORD string = "INCRRECT_PASSWORD"
const OFFSET_MUST_BE_NUMBER string = "OFFSET_MUST_BE_NUMBER"
const LIMIT_MUST_BE_NUMBER string = "LIMIT_MUST_BE_NUMBER"
const INVALID_PARAMETERS string = "INVALID_PARAMETERS"
const INVALID_TOKEN string = "INVALID_TOKEN"
